version: '3.8'

services:
  transcriptor:
    build:
      context: .
    environment:
      - PORT=8000
    labels:
      - traefik.enable=true
      - traefik.http.routers.transcriptor.rule=Host(`reuniao.procexai.tech`)
      - traefik.http.routers.transcriptor.entrypoints=websecure
      - traefik.http.routers.transcriptor.tls.certresolver=le
      - traefik.http.services.transcriptor.loadbalancer.server.port=8000
    networks:
      - traefik_public
      - digital_network
    ports:
      - "8000:8000"

networks:
  traefik_public:
    external: true
  digital_network:
    external: true
